[[plugins]]
  package = '@netlify/plugin-gatsby'
[build]
  publish = 'public'
  command = 'gatsby build'
[build.environment]
  NODE_VERSION = '16.13.0'
  YARN_VERSION = '1.22.15'
  YARN_FLAGS = '--no-ignore-optional'
