export { default as About } from './about'
export { default as Hero } from './hero'
export { default as Posts } from './posts'
export { default as Social } from './social'
export { default as Section } from './section'